services:
  mariadb:
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
  # Websockets
  soketi:
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_METRICS_SERVER_PORT: '9601'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
